project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!/lab-activities"

website:
  page-navigation: true
  title: "Introduction to Data Science"
  description: "Homepage for DATA 301 at Cal Poly"
  site-url: "https://github.com/atheobold/data-301"
  repo-url: https://github.com/atheobold/data-301
  repo-actions: [issue]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Allison Theobold"
    background: "#D9E3E4"

  sidebar:
    background: "#5D737E"
    logo: "images/allison-horst-black.jpg"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/atheobold/data-301
        text: "GitHub organization"
      - icon: person-fill
        href: https://canvas.calpoly.edu
        text: "Cal Poly Canvas"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-materials/syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
      - section: "Lecture Slides"
        contents:
          - href: slides/00-welcome.qmd
            text: "Week 0 - Welcome & Course Set-up"
          - href: slides/01-tabular-data-summaries.qmd
            text: "Week 1, Part 1 - Tabular Data and Variable Summaries"
          - href: slides/02-conditional-distributions.qmd
            text: "Week 1, Part 2 - Visualizing and Comparing Categorical Variables"
          - href: slides/03-quantitative-variables.qmd
            text: "Week 2, Part 1 - Visualizing and Summarizing Quantitative Variables"
          - href: slides/04-group-by.qmd
            text: "Week 2, Part 2 - Multivariate Summaries"
          - href: slides/05-distances.qmd
            text: "Week 3 - Distances Between Observations"
          - href: slides/06-preprocessing.qmd
            text: "Week 4, Part 1 - Dummy Variables & Column Transformers"
          - href: slides/07-text-data.qmd
            text: "Week 4, Part 2 - Bag-of-Words and TF-IDF"
          - href: slides/08-knn.qmd
            text: "Week 5 Part 1 - KNN"
          - href: https://docs.google.com/presentation/d/1ZIBJzHWQFJtsQzkak0W-Z5RxT-0wSrvGPckXxhs8M-c/edit?usp=sharing
            text: "Week 5 Part 2 - Spicing Up Your Visualizations"
          - href: slides/09-modeling.qmd
            text: "Week 6, Part 1 - Introduction to Modeling"
          - href: slides/10-cross-val.qmd
            text: "Week 6, Part 2 - Cross Validation & Grid Search"
          - href: slides/11-classification.qmd
            text: "Week 7, Part 1 - Classification"
          - href: slides/12-logistic.qmd
            text: "Week 7, Part 2 - Logistic Regression"
          - href: slides/13-kmeans.qmd
            text: "Week 8, Part 1 - Unsupervised Learning"
          - href: slides/14-merge.qmd
            text: "Week 8, Part 2 - Combining Datasets"
          # - href: weeks/week-10.qmd
          #   text: "Week 10"
      # - section: "Lab Assignments"
      #   contents:
      #     - href: labs/instructions/lab-1-instructions.qmd
      #       text: "Lab 1 Instructions"
          # - href: labs/instructions/lab-2-instructions.qmd
          #   text: "Lab 2 Instructions"
          # - href: labs/instructions/challenge-2-instructions.qmd
          #   text: "Challenge 2 Instructions"
          # - href: labs/instructions/lab-3-instructions.qmd
          #   text: "Lab 3 Instructions"
          # - href: labs/instructions/challenge-3-instructions.qmd
          #   text: "Challenge 3 Instructions"
          # - href: labs/instructions/lab-4-instructions.qmd
          #   text: "Lab 4 & Challenge 4 Instructions"
          # - href: labs/instructions/lab-5-instructions.qmd
          #   text: "Lab 5 Instructions"
          # - href: labs/instructions/lab-7-instructions.qmd
          #   text: "Lab 7 Instructions"
          # - href: labs/instructions/challenge-7-instructions.qmd
          #   text: "Challenge 7 Instructions"
          # - href: labs/instructions/lab-8-instructions.qmd
          #   text: "Lab 8 Instructions"
          # - href: labs/instructions/lab-9-instructions.qmd
          #   text: "Lab 9 Instructions"
      # - section: "Gallary of Student Work"
      #   contents:
      #     - href: labs/exemplars/student-work.qmd
      #       text: "Exemplary Student Work"

format:
  html:
    theme:
      light: [cosmo, style/stat331.scss]
      dark: [cosmo, style/stat331.scss, style/dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    linkcolor: "#5D737E"

editor: visual