---
title: "Introduction to Data Science (in Python)"
tbl-colwidths: [5,15,30,20,20,20,20]
---

This page contains an outline of the topics, content, and assignments for the quarter. Note that this schedule will be updated as the quarter progresses, with all changes documented here.

<!-- TODO: Switch to spreadsheet for content (like Mine and Maria do) -->

+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| Week                                          | Date                             | Required Reading | Lecture Slides                                                                                                                                             | Lab Activity                                                                                                                                           | Weekly Assignment     | Exams & Project           |
+===============================================+==================================+==================+============================================================================================================================================================+========================================================================================================================================================+=======================+===========================+
| 0                                             | Sunday, January 5                |                  | [Welcome to DATA 301!](/slides/00-welcome.qmd "Welcome to DATA 301!")                                                                                      |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 1 Summarizing Tabular Data                    | Tuesday, January 7               |                  | [Tabular Data & Variable Summaries](/slides/01-tabular-data-summaries.qmd "Tabular Data & Variable Summaries")                                             | [Activity 1.1 (Link to Collab)](https://colab.research.google.com/drive/1L7vRYObMyqvWWlFaEnZqEJQjpHsWu690?usp=sharing "Activity 1.1 (Link to Collab)") |                       |                           |
|                                               |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
|                                               |                                  |                  | [GenAI Activity (Link to Collab)](https://colab.research.google.com/drive/1QNGwd_33HqvANn4ZO8BVbCvmnzMJd28c?usp=sharing "GenAI Activity (Link to Collab)") |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, January 9              |                  | [Visualizing and Comparing Categorical Variables](/slides/02-conditional-distributions.qmd "Visualizing and Comparing Categorical Variables")              | [Activity 1.2 (Link to Collab)](https://colab.research.google.com/drive/1zD_efmvaO_lkwoCrKBMuubznKIt9k_Ia?usp=sharing "Activity 1.2 (Link to Collab)") |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, January 10               |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 1 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 2 Summarizing & Visualizing Quantitative Data | Tuesday, January 14              |                  | [Visualizing and Summarizing Quantitative Variables](/slides/03-quantitative-variables.qmd "Visualizing and Summarizing Quantitative Variables")           | [Activity 2.1 (Link to Collab)](https://colab.research.google.com/drive/1XBzyo6WxGv9JesWvFl-JoMsk_fIIwZHs?usp=sharing "Activity 2.1 (Link to Collab)") |                       |                           |
|                                               |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
|                                               | (Dr. T's b-day)                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, January 16             |                  | [Multivariate Summaries](/slides/04-group-by.qmd "Multivariate Summaries")                                                                                 | Activity 2.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, January 17               |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 2 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 3\                                            | Tuesday, January 21              |                  |                                                                                                                                                            | Activity 3.1                                                                                                                                           |                       |                           |
| Measuring Similarity with Distances           |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, January 23             |                  |                                                                                                                                                            | Activity 3.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, January 24               |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 3 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 4\                                            | Tuesday, January 28              |                  |                                                                                                                                                            | Activity 4.1                                                                                                                                           |                       |                           |
| if-idf & k-nearest neighbors                  |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, January 30             |                  |                                                                                                                                                            | Activity 4.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, January 31               |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 4 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 5\                                            | Tuesday, February 4              |                  |                                                                                                                                                            | Activity 5.1                                                                                                                                           |                       |                           |
| Intro to Modeling & Midterm Exam              |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, February 6             |                  |                                                                                                                                                            | Activity 5.2                                                                                                                                           |                       | Midterm Exam (in-class)   |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, February 7               |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 5 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 6\                                            | Tuesday, February 11             |                  |                                                                                                                                                            | Activity 6.1                                                                                                                                           |                       |                           |
| Model Selection & Classification              |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, February 13            |                  |                                                                                                                                                            | Activity 6.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, February 14              |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 6 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 7\                                            | Tuesday, February 18             |                  |                                                                                                                                                            | Activity 7.1                                                                                                                                           |                       |                           |
| Logistic Regression & Unsupervised Learning   |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, February 20            |                  |                                                                                                                                                            | Activity 7.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, February 21              |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 7 Due by Midnight | Project Proposal Due      |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 8\                                            | Tuesday, February 25             |                  |                                                                                                                                                            | Activity 8.1                                                                                                                                           |                       |                           |
| Joining Data & Hierarchical Data              |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, February 27            |                  |                                                                                                                                                            | Activity 8.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, February 28              |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 8 Due by Midnight |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 9\                                            | Tuesday, March 4                 |                  |                                                                                                                                                            | Activity 9.1                                                                                                                                           |                       |                           |
| Webscraping                                   |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, March 6                |                  |                                                                                                                                                            | Activity 9.2                                                                                                                                           |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Friday, March 7                  |                  |                                                                                                                                                            |                                                                                                                                                        | Lab 9 Due by Midnight | Posters Due to be Printed |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| 10\                                           | Tuesday, March 11                |                  |                                                                                                                                                            | Activity 10.1                                                                                                                                          |                       |                           |
| Chloropleths & Final Exam                     |                                  |                  |                                                                                                                                                            |                                                                                                                                                        |                       |                           |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
|                                               | Thursday, March 13               |                  |                                                                                                                                                            |                                                                                                                                                        |                       | Final Exam (in-class)     |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
| Finals Week                                   | Saturday, March 15 10:10am - 1pm |                  |                                                                                                                                                            |                                                                                                                                                        |                       | Poster Presentations      |
+-----------------------------------------------+----------------------------------+------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------+---------------------------+
