---
title: "Making your Data Visualizations More Effective"
format: html
---

# Child Care Data

```{r}
library(tidyverse)

childcare_costs <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-09/childcare_costs.csv')

counties <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-05-09/counties.csv')
```

## Join + Clean Data

```{r}
ca_childcare <- full_join(counties,
                 childcare_costs,
                 ) |> 
  filter(state_abbreviation == "CA",
         county_name %in% c("San Luis Obispo County", 
                            "Orange County", 
                            "San Francisco County")
         ) |> 
  pivot_longer(cols = starts_with("mfcc_"),
               names_to = "development_stage",
               values_to = "median_weekly_childcare_cost") |>
  filter(development_stage %in% c("mfcc_infant", "mfcc_toddler")) |> 
  mutate(across(.cols = c(county_name, state_abbreviation, development_stage), 
                .fns = ~ as.factor(.x)
                ),
         development_stage = as.factor(str_remove(development_stage, pattern = "mfcc_"))
         ) |> 
  select(county_name, study_year, development_stage, median_weekly_childcare_cost)

#write_csv(ca_childcare, file = "ca_childcare_clean.csv")
```

## Childcare Costs over Time Bar Plot

```{r}
ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             fill = county_name)
         ) +
  geom_bar(stat = "identity",
           position = "dodge") +
  facet_wrap(~ development_stage) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_fill_brewer(palette = "Accent") +
  theme_bw() +
  labs(x = "Year",
       y = "Weekly Median Childcare Cost ($)",
       fill = "County")
```

## Childcare Costs over Time Line Graph

```{r}
ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             color = development_stage,
             shape = development_stage)
  ) +
  geom_point() +
  geom_line() +
  facet_wrap(~ county_name) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_color_manual(values = c("steelblue", "orange3")) +
  theme_bw() +
  labs(x = "Year",
       y = "Weekly Median Childcare Cost ($)",
       color = "Development \nStage",
       shape = "Development \nStage")
```

## Childcare Costs over Time Line Graph One Column

```{r}
ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             color = development_stage,
             shape = development_stage)
  ) +
  geom_point() +
  geom_line() +
  facet_wrap(~ county_name, ncol = 1) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_color_manual(values = c("steelblue", "orange3")) +
  theme_bw() +
  labs(x = "Year",
       y = "Weekly Median Childcare Cost ($)",
       color = "Development \nStage",
       shape = "Development \nStage")
```

## Removing y-axis label

```{r}
ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             color = development_stage,
             shape = development_stage)
  ) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::label_dollar()) +
  facet_wrap(~ county_name, ncol = 1) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_color_manual(values = c("steelblue", "orange3")) +
  theme_bw() +
  labs(x = "Year",
       y = "",
       title = "Weekly Median Cost of Childcare by CA County",
       color = "Development \nStage",
       shape = "Development \nStage")
```

## Moving Legend

```{r}
ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             color = development_stage,
             shape = development_stage)
  ) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::label_dollar()) +
  facet_wrap(~ county_name, ncol = 1) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_color_manual(values = c("steelblue", "orange3")) +
  theme_bw() +
  theme(legend.position = "top") +
  labs(x = "Year",
       y = "",
       title = "Weekly Median Cost of Childcare by CA County",
       color = "by Development Stage",
       shape = "by Development Stage")
```

## Removing Legend

```{r}

legend_text <- ca_childcare %>% 
  filter(county_name == "San Francisco County", 
         study_year %in% c(2012, 2014)
         ) %>% 
  group_by(development_stage) %>% 
  mutate(plot_year = if_else(development_stage == "infant",
                             2012, 
                             2014), 
         plot_median = if_else(development_stage == "infant", 
                               median_weekly_childcare_cost + 50, 
                               median_weekly_childcare_cost - 15)
         ) %>% 
  distinct(plot_year, development_stage, .keep_all = TRUE)

ca_childcare |> 
  ggplot(aes(x = study_year,
             y = median_weekly_childcare_cost,
             color = development_stage,
             shape = development_stage)
  ) +
  geom_point() +
  geom_line() +
  scale_y_continuous(labels = scales::label_dollar()) +
  facet_wrap(~ county_name, ncol = 1) +
  scale_x_continuous(breaks = seq(2008, 2018, 2)) +
  scale_color_manual(values = c("steelblue", "orange3")) +
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "Year",
       y = "",
       title = "Weekly Median Cost of Childcare by CA County",
       subtitle = "by Development Stage",
       shape = "", 
       color = "") +
  geom_text(data = legend_text, 
            mapping = aes(x = plot_year, 
                          y = plot_median, 
                          color = development_stage, 
                          label = development_stage)
            )

# Makes the same annotation for each facet!
  # annotate(geom = "text", 
  #          x = 2012, 
  #          y = 250, 
  #          color = "steelblue", 
  #          label = "infant"
  #          )
```